### PR TITLE
handle pinentry protocol spec for encoded entities

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by apiology** [comment]
Thanks for the contribution!

Have you tested against both Python 2.7 and 3.x?

**Comment by ghost** [comment]
~I did by hand, but I'm happy to commit tox tests to reflect that too~ thought I did, python 2.7 is sutpid

**Comment by ghost** [comment]
I don't know your feelings on `six`, since this project is so thin an security oriented I thought doing the try/catch on import might be preferred; though I would agree that catching ImportError like this could be considered wrong behaviour, I'm not sure it could be used to inject an arbitrary package since urllib is part of the stdlib; but i'm not going to say it's impossible. 

Thoughts on how to do fall-back imports best? I could also do an explicit python version check and import based on the condition

**Comment by ghost** [comment]
oh so I just noticed, the `_esc` functional already does `x.replace("%", "%25").replace("\n", "%0A")`; I [didn't fully understand the C routine](https://github.com/gpg/pinentry/blob/master/pinentry/pinentry.c#L392) that percent encodes passwords, which is why I am using url unquote under the impression that the api contract is "we may url quote things" - if someone better understands the possible values to decode it might be tenable to just decode a handful without invoking urllib

**Comment by apiology** [comment]
Thanks, @ava-dylang!  This does seem to be a move in the right direction, and I think the approach to Python 2 support seems right to me.

But...how can I reproduce the problem that this fixes?  I tried with an emoji (which was rejected both before and after) and with `%` (which worked correctly both before and after).

(I tried with pinentry-mac, which maybe has different behavior?)

**Comment by apiology** [comment]
(oh, and if you wouldn't mind merging the conflict from the other PR...)

**Comment by ghost** [comment]
To show the underlying pinentry behaviour as I observe it:
when entering a literal `%` into any of pinentry program I get a `%25` in the D reply, this can be show on my systems by running
```
$ pinentry-tty <enter>
getpin <enter>
% <enter>
bye <enter>
```
which looks like this with output included:
```
$ pinentry-tty
OK Pleased to meet you
getpin
Enter your passphrase.
PIN: 
D %25
OK
bye
OK closing connection
```

I don't know how pinentry-mac is distributed, the first source code I found on google looks like it should be percent escaping special chars all the same:
https://github.com/GPGTools/pinentry-mac/blob/8d811e25d58e88d804f61e2bcba3b0b2ddef402f/Source/pinentry-0.9.4/pinentry/pinentry.c#L873

**Comment by ghost** [comment]
to show the behaviour change (and that i tested this commit)
pysectools version v0.5.0 (old behavior)

> ```
> $ git checkout v0.5.0 
> Note: checking out 'v0.5.0'.
> HEAD is now at 5799337... Prepare for release
> ```
> 
> python 3.5.1-3 (ubuntu xenial)
> ```
> $ ~/prefix/pysectools ((v0.5.0)) $ python3
> Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
> [GCC 5.4.0 20160609] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pysectools.pinentry
> >>> pysectools.pinentry.__file__
> '/homedir/prefix/pysectools/pysectools/pinentry.py'
> >>> pysectools.pinentry.Pinentry().ask()
> '%25'
> >>> exit()
> ```
> 
> python 2.7.12-1~16.04 (uubntu xenial-updates)
> ```
> $ ~/prefix/pysectools ((v0.5.0)) $ python2
> Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
> [GCC 5.4.0 20160609] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pysectools.pinentry
> >>> pysectools.pinentry.__file__
> 'pysectools/pinentry.pyc'
> >>> pysectools.pinentry.Pinentry().ask()
> u'%25'
> >>> exit()
> $ ~/prefix/pysectools ((v0.5.0)) $ 
> 
> ```

this pr
> ```
> git checkout 895d3ad5155929d3299d90fb110dfab4bb909b5e
> ```
> 
> python 3.5.1-3 (ubuntu xenial)
> ```
> $ ~/prefix/pysectools ((895d3ad...)) $ python3
> Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
> [GCC 5.4.0 20160609] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pysectools.pinentry
> >>> pysectools.pinentry.__file__
> '/homedir/prefix/pysectools/pysectools/pinentry.py'
> >>> pysectools.pinentry.Pinentry().ask()
> '%'
> >>> exit()
> ```
> 
> python 2.7.12-1~16.04 (uubntu xenial-updates)
> ```
> $ ~/prefix/pysectools ((895d3ad...)) $ python2
> Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
> [GCC 5.4.0 20160609] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pysectools.pinentry
> >>> pysectools.pinentry.__file__
> 'pysectools/pinentry.py'
> >>> pysectools.pinentry.Pinentry().ask()
> u'%'
> >>> exit()
> ```

**Comment by apiology** [comment]
Hmmm, I must have had things confused before, as yeah, I can reproduce now.  Thanks for the PR, @ava-dylang!

**Comment by apiology** [comment]
Just published v0.5.1 to PyPI

**Pull request merged**
